# Generated by Django 4.2.9 on 2024-01-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='room',
            new_name='chatroom',
        ),
    ]
